services:
  jenkins:
    build: ./jenkins
    container_name: jenkins-ci
    user: root  # Necessário para acessar o docker.sock sem conflito de permissões
    privileged: true
    ports:
      - "8080:8080"
    environment:
      # CORREÇÃO: Altere esta linha para o caminho padrão (Linux/Windows com Docker Desktop)
      DOCKER_HOST: unix:///var/run/docker.sock
      JENKINS_HOME_HOST: ./jenkins_home
      TZ: Etc/GMT+3
    volumes:
      - ./jenkins_home:/var/jenkins_home
      # CORREÇÃO: Garanta que o socket do host esteja mapeado neste caminho
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      # - kind
    restart: unless-stopped