services:
  jenkins:
    build: ./jenkins
    container_name: jenkins-ci
    user: root
    privileged: true
    ports:
      - "8080:8080"
    environment:
      # CORREÇÃO PARA WINDOWS:
      DOCKER_HOST: unix:///var/run/docker.sock
      JENKINS_HOME_HOST: ./jenkins_home
      TZ: Etc/GMT+3
    volumes:
      - ./jenkins_home:/var/jenkins_home
      # CORREÇÃO PARA WINDOWS:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
    restart: unless-stopped